### ISSUE TITLE
As a user, I want to be able to edit a group packing list that is synchronized with the other participating users, so that everybody knows what to take to an appointment, and an individual packing list. I also want to delete a packing item if I added it incorrectly for example, so that no errors are there.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#10]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/client#27
- [x] sopra-fs24-group-11/client#26
- [x] sopra-fs24-group-11/client#28
- [x] sopra-fs24-group-11/client#29
- [x] sopra-fs24-group-11/client#30 
- [x] sopra-fs24-group-11/client#31 
- [x] sopra-fs24-group-11/server#106
- [x] sopra-fs24-group-11/server#107
- [x] sopra-fs24-group-11/server#108
## SE Tasks:

**Priority:** high  
**Estimate:** 8h
