### ISSUE TITLE
As a user, I want to be able to have a common To-Do list with other users so that everybody knows what needs to be organized/done (e.g., call a hotel, reserve a restaurant). Tasks can be distributed between users, and there is an individual view where everybody sees the tasks given to them.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#11]
## Acceptance Criteria / Definition of Done:
- [ ] A user should immediately see changes in the to-do list done by other users.
- [ ] By clicking on a task, one or various users responsible for it can be selected.
- [ ] The users can mark a task as done, which marks it as done for all users.
- [ ] There is an individual section which is not synched with other users.
- [ ] By clicking on delete button, elements can be deleted out of the to-do list.

## SE Tasks:

**Priority:** high  
**Estimate:** 12h
