### ISSUE TITLE
As a user, I want to receive messages about any changes in the trip so that I am informed and can adjust my plans accordingly.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#13]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/client#41
- [x] sopra-fs24-group-11/server#76
- [x] sopra-fs24-group-11/client#42
- [x] sopra-fs24-group-11/server#78
- [x] sopra-fs24-group-11/server#112

## SE Tasks:
- The log can be displayed in a scrollable list.

**Priority:** medium  
**Estimate:** 10h
