### ISSUE TITLE
As a user, I want to have a trip history in my dashboard so that I can access each past trip and review what we did and who was with me.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#15]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/client#47
- [x] sopra-fs24-group-11/client#50
- [x] sopra-fs24-group-11/client#48
- [x] sopra-fs24-group-11/server#87
- [x] sopra-fs24-group-11/server#114
- [x] sopra-fs24-group-11/client#49

## SE Tasks:
- Since each trip has a tripId, we can just open the site …/trip/{tripId} and display the finished trip.

**Priority:** medium  
**Estimate:** 6h
