### ISSUE TITLE
As a registered user, I want to access my profile where I can see my personal data and update some of it (for now: email, username, birthday). I also want to set a profile picture and be able to delete my account if I don’t want to use the service again.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#2]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/client#62
- [x] sopra-fs24-group-11/client#3
- [x] sopra-fs24-group-11/server#30
- [x] sopra-fs24-group-11/client#4
- [x] sopra-fs24-group-11/server#32
- [x] sopra-fs24-group-11/client#5
- [x] sopra-fs24-group-11/server#117
- [x] sopra-fs24-group-11/server#118

## SE Tasks:
- Input fields. Maximum storage size of picture or automatic resizing when uploading.

**Priority:** critical  
**Estimate:** 12h
