### ISSUE TITLE
As a user, I want to make friend requests and see my already added friends so that I can invite them faster to a new trip and stay connected with them.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#4]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/client#12
- [x] sopra-fs24-group-11/client#11
- [x] sopra-fs24-group-11/server#41
- [x] sopra-fs24-group-11/server#97 
- [x]  sopra-fs24-group-11/server#98
## SE Tasks:
- Suggest matching usernames depending on user input.

**Priority:** critical  
**Estimate:** 8h

![image](https://github.com/sopra-fs24-group-11/server/assets/120049684/a148bd88-bb97-42bb-9fd4-8fad3ad1f84c)
