### ISSUE TITLE
As a user, I want to enter a station name of public transport into the start field and the system should provide me with suggestions matching the string so that I can choose one of them as my starting point. As a trip creator, I want the same functionality for the trip destination.

### ISSUE THREAD

**Issue by jxnjo** [sopra-fs24-group-11/server#7]
## Acceptance Criteria / Definition of Done:
- [x] sopra-fs24-group-11/server#44
- [x] sopra-fs24-group-11/client#17
- [x] sopra-fs24-group-11/client#18
- [x] sopra-fs24-group-11/client#19
- [x] sopra-fs24-group-11/server#101
- [x] sopra-fs24-group-11/client#20
- [x] sopra-fs24-group-11/server#102
- [x] sopra-fs24-group-11/client#21
- [x] sopra-fs24-group-11/server#103
- [x] sopra-fs24-group-11/server#119

## SE Tasks:
- [x] Translate Location Names to Station Code! Maybe store all in Database.

**Priority:** critical  
**Estimate:** 15h
